version: 2
updates:
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: daily
      time: "12:10"
      timezone: Europe/Paris

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: daily
      time: "12:10"
      timezone: Europe/Paris
  
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: daily
      time: "12:10"
      timezone: Europe/Paris