name: Semgrep job
on:
    push:
        branches: main
jobs:
    semgrep:
        name: Semgrep
        runs-on: ubuntu-latest
        container:
            image: returntocorp/semgrep:1.1.0
        if: (github.actor != 'dependabot[bot]')
        steps:
            - name: "checkout source"
              uses: actions/
            - name: "Exécute semgrep"
              run: semgrep ci
              env:
                SEMGREP_RULES: p/default
