name: "Super linter"
on:
    pull_request:
        branches: [main]
jobs:
    lint:
        name: Lint code
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: use linter
          uses: github/super-linter/slim@v4
          env:
            VALIDATE_ALL_CODEBASE: true
            GITHUB: ${{ secrets.GITHUB_TOKEN }}
        